// src/app/(main)/chat/page.tsx
// /src/app/(main)/chat/page.tsx
"use client";

import { generateConversationalResponse } from "@/ai/flows/generate-conversational-response";
import { generateDailyEmotionalSummary } from "@/ai/flows/generate-daily-emotional-summary";
import { extractUserFacts } from "@/ai/flows/extract-user-facts";
import { Avatar, AvatarFallback } from "@/components/ui/avatar";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { ScrollArea } from "@/components/ui/scroll-area";
import { Alert, AlertDescription, AlertTitle } from "@/components/ui/alert";
import { Tooltip, TooltipContent, TooltipProvider, TooltipTrigger } from "@/components/ui/tooltip";
import { useToast } from "@/hooks/use-toast";
import { cn } from "@/lib/utils";
import { useAppStore, type Message, type DailySummary } from "@/lib/store";
import { Send, User, Loader2, BookCheck, WifiOff, Mic, AlertTriangle, Clock, RefreshCw } from "lucide-react";
import { FormEvent, useState, useRef, useEffect } from "react";
import { motion, AnimatePresence } from "framer-motion";
import { HerLogo } from "@/components/ui/her-logo";
import { useLanguage } from "@/hooks/use-language";
import { retryWithBackoff } from "@/lib/retry";

// Declare SpeechRecognition types for cross-browser compatibility
declare global {
  interface Window {
    SpeechRecognition: any;
    webkitSpeechRecognition: any;
  }
}

const MESSAGE_LIMIT = 20; // Example: 20 user messages per day
const WARNING_THRESHOLD = 5; // Show warning when 5 messages are left

export default function ChatPage() {
  const { 
    messages, addMessage, initializeMessages, getConversationHistory, 
    userFacts, addFact, getTodaysUserMessageCount, addSummary,
    getDatesNeedingSummary, getConversationForDate, clearChatHistory,
    updateInitialMessage,
    hasDoneTarotReadingToday, setLastTarotReadingDate,
    userName, userGender, oraclePersonality,
    processOfflineQueue, updateMessageStatus
  } = useAppStore();

  const [input, setInput] = useState("");
  const [isLoading, setIsLoading] = useState(false);
  const [isSummarizing, setIsSummarizing] = useState(false);
  const [isOnline, setIsOnline] = useState(true);
  const { dict, language } = useLanguage();
  
  // Speech Recognition state
  const [isListening, setIsListening] = useState(false);
  const [isMicAvailable, setIsMicAvailable] = useState(false);
  const recognitionRef = useRef<any>(null);


  const [datesToSummarize, setDatesToSummarize] = useState<string[]>([]);
  
  const { toast } = useToast();
  const messagesEndRef = useRef<HTMLDivElement>(null);

  const userMessageCount = getTodaysUserMessageCount ? getTodaysUserMessageCount() : 0;
  const messagesLeft = MESSAGE_LIMIT - userMessageCount;
  const isLimitReached = messagesLeft <= 0;
  const shouldShowLimitNotice = messagesLeft <= WARNING_THRESHOLD;
  const shouldShowSummaryButton = (datesToSummarize?.length ?? 0) > 0 || isLimitReached;
  
  // Initialize Speech Recognition
  useEffect(() => {
    const SpeechRecognition = window.SpeechRecognition || window.webkitSpeechRecognition;
    if (SpeechRecognition) {
      setIsMicAvailable(true);
      const recognition = new SpeechRecognition();
      recognition.continuous = false; // Process after each pause
      recognition.interimResults = false; // Only get final results
      recognition.lang = language === 'es' ? 'es-ES' : 'en-US';

      recognition.onresult = (event: any) => {
        const transcript = event.results[event.results.length - 1][0].transcript;
        setInput(prevInput => (prevInput ? prevInput + ' ' : '') + transcript.trim());
      };

      recognition.onerror = (event: any) => {
        console.error("Speech recognition error", event.error);
        if (event.error === 'not-allowed' || event.error === 'service-not-allowed') {
            toast({
                variant: 'destructive',
                title: dict.chat.speechErrorTitle,
                description: dict.chat.speechPermissionDenied,
            });
        }
        setIsListening(false);
      };

      recognition.onend = () => {
        setIsListening(false);
      };
      
      recognitionRef.current = recognition;
    }
  }, [toast, language, dict]);


  const toggleListening = () => {
    if (isListening) {
      recognitionRef.current?.stop();
    } else {
      navigator.mediaDevices.getUserMedia({ audio: true })
        .then(() => {
          try {
            recognitionRef.current?.start();
            setIsListening(true);
          } catch(e) {
            console.error("Could not start recognition", e)
            setIsListening(false);
          }
        })
        .catch(err => {
          console.error('Mic permission error:', err);
          toast({
              variant: 'destructive',
              title: dict.chat.speechErrorTitle,
              description: dict.chat.speechPermissionDenied,
          });
        });
    }
  };

  // Effect to process offline queue when connection is restored
  useEffect(() => {
    const handleOnline = () => {
      setIsOnline(true);
      toast({ title: dict.chat.online.title, description: dict.chat.online.description });
      processOfflineQueue();
    };
    const handleOffline = () => setIsOnline(false);

    if (typeof navigator !== 'undefined') {
      setIsOnline(navigator.onLine);
    }

    window.addEventListener('online', handleOnline);
    window.addEventListener('offline', handleOffline);

    return () => {
      window.removeEventListener('online', handleOnline);
      window.removeEventListener('offline', handleOffline);
      if (recognitionRef.current) {
        recognitionRef.current.onend = null;
        recognitionRef.current.stop();
      }
    };
  }, [processOfflineQueue, toast, dict]);

  useEffect(() => {
    if (getDatesNeedingSummary) {
      const dates = getDatesNeedingSummary();
      setDatesToSummarize(dates);
    }
  }, [messages, getDatesNeedingSummary]);

  useEffect(() => {
    if (initializeMessages) {
        initializeMessages(dict.chat.initialMessage);
    }
  }, [initializeMessages, dict.chat.initialMessage]);

  useEffect(() => {
      if (updateInitialMessage) {
          updateInitialMessage(dict.chat.initialMessage)
      }
  }, [dict.chat.initialMessage, updateInitialMessage]);
  
  useEffect(() => {
    messagesEndRef.current?.scrollIntoView({ behavior: "smooth" });
  }, [messages]);

  const handleSendMessage = async (messageContent: string, messageId: string) => {
    updateMessageStatus(messageId, 'pending');
    setIsLoading(true);
    
    try {
      const operation = () => generateConversationalResponse({
        message: messageContent,
        conversationHistory: getConversationHistory ? getConversationHistory() : "",
        userFacts: (userFacts || []).map(f => f.fact),
        language: language,
        tarotReadingDone: hasDoneTarotReadingToday ? hasDoneTarotReadingToday() : false,
        userName,
        userGender,
        personality: oraclePersonality
      });

      const result = await retryWithBackoff(operation);
      
      const aiMessage: Message = { role: "assistant", content: result.response, id: crypto.randomUUID(), status: 'sent' };
      addMessage ? addMessage(aiMessage) : '';
      updateMessageStatus(messageId, 'sent');

      // Heuristic to check if a reading was done.
      const readingKeywords = ['past:', 'presente:', 'futuro:'];
      const lowerCaseResponse = result.response.toLowerCase();
      
      if (!hasDoneTarotReadingToday() && readingKeywords.some(kw => lowerCaseResponse.includes(kw))) {
        if (setLastTarotReadingDate) {
          setLastTarotReadingDate(new Date().toISOString());
        }
      }

    } catch (error) {
      console.error("Error generating response after retries:", error);
      updateMessageStatus(messageId, 'failed');
      // Do not add an AI error message to the chat, the user can just retry.
      toast({ variant: "destructive", title: dict.chat.responseErrorTitle, description: dict.chat.responseErrorDesc });
    } finally {
      setIsLoading(false);
    }
  }

  const handleSubmit = async (e: FormEvent) => {
    e.preventDefault();
    if (isListening) {
      recognitionRef.current?.stop();
      setIsListening(false);
    }
    if (!input.trim() || isLoading || isLimitReached) return;

    const messageContent = input;
    setInput("");
    
    const userMessage: Omit<Message, 'id' | 'timestamp'> = { 
        role: "user", 
        content: messageContent, 
        status: isOnline ? 'pending' : 'pending' // Always pending at first
    };
    const messageId = addMessage(userMessage);

    if (isOnline) {
      await handleSendMessage(messageContent, messageId);
    } else {
      toast({ title: dict.chat.offline.title, description: dict.chat.offline.description });
    }
  };

  const handleRetryMessage = (message: Message) => {
      if(isOnline) {
        handleSendMessage(message.content, message.id);
      } else {
        toast({ variant: "destructive", title: "Still Offline", description: "Cannot retry message. Please check your connection." });
      }
  }
  
  const handleGenerateSummary = async () => {
    if (!isOnline) {
      toast({
        variant: "destructive",
        title: dict.common.offlineErrorTitle,
        description: dict.summary.offlineErrorDesc,
      });
      return;
    }

    const datesToProcess = isLimitReached ? [new Date().toISOString().split('T')[0], ...datesToSummarize] : datesToSummarize;
    const uniqueDates = [...new Set(datesToProcess)];

    if (uniqueDates.length === 0) return;

    setIsSummarizing(true);
    toast({
        title: dict.summary.manualGenerate.title,
        description: dict.summary.manualGenerate.desc
    });

    let newFactsFound = false;

    for (const date of uniqueDates) {
        try {
            const conversation = getConversationForDate ? getConversationForDate(date) : null;
            if (!conversation) continue;

            // 1. Generate Summary
            const summaryResult = await generateDailyEmotionalSummary({
                conversationHistory: conversation,
                userFacts: (userFacts || []).map(f => f.fact),
                language,
            });

            const newSummary: DailySummary = {
                id: crypto.randomUUID(),
                date: date,
                ...summaryResult,
            };
            if(addSummary) addSummary(newSummary);

            // 2. Extract Facts
            const knownFacts = (userFacts || []).map(f => f.fact);
            const factResult = await extractUserFacts({ conversationHistory: conversation, existingFacts: knownFacts });
            
            if (factResult.facts.length > 0) {
              newFactsFound = true;
              factResult.facts.forEach(fact => {
                if (addFact) addFact({ id: crypto.randomUUID(), fact });
              });
            }
        } catch (error) {
            console.error(`Error processing summary/facts for ${date}:`, error);
        }
    }
    
    setDatesToSummarize([]);
    setIsSummarizing(false);

    if (clearChatHistory) {
      clearChatHistory(dict.chat.initialMessage);
    }

    toast({
        title: dict.summary.manualGenerate.successTitle,
        description: dict.summary.manualGenerate.successDesc
    });

    if (newFactsFound) {
      toast({
        title: dict.chat.factExtraction.title,
        description: dict.chat.factExtraction.description,
      });
    }
  };

  const getPlaceholderText = () => {
    if (isListening) return dict.chat.listening;
    if (isLimitReached) return dict.chat.limitReached;
    if (datesToSummarize.length > 0) return dict.summary.manualGenerate.disabledPlaceholder;
    return dict.chat.placeholder;
  };

  const isChatDisabled = isLoading || isSummarizing || (isOnline && (datesToSummarize?.length ?? 0) > 0) || isLimitReached;
  
  return (
    <div className="flex flex-col h-full bg-background/80 backdrop-blur-sm rounded-lg border border-primary/20 shadow-lg shadow-primary/10">
      <ScrollArea className="flex-1 p-4">
        <div className="space-y-6">
         <TooltipProvider>
          <AnimatePresence initial={false}>
            {(messages || []).map((message) => (
              <motion.div
                key={message.id}
                layout
                initial={{ opacity: 0, y: 20 }}
                animate={{ opacity: 1, y: 0 }}
                exit={{ opacity: 0, y: -20 }}
                transition={{ duration: 0.3, ease: 'easeOut' }}
                className={cn(
                  "flex items-start gap-4",
                  message.role === "user" ? "justify-end" : "justify-start"
                )}
              >
                {message.role === "assistant" && (
                  <Avatar className="border-2 border-primary/50 shadow-md shadow-primary/20">
                    <AvatarFallback className="bg-transparent text-primary">
                       <HerLogo className="h-6 w-6" />
                    </AvatarFallback>
                  </Avatar>
                )}
                <div
                  className={cn(
                    "max-w-md rounded-xl px-4 py-3 text-sm shadow-md",
                    message.role === "user" ? "bg-primary text-primary-foreground shadow-primary/30" : "bg-card text-card-foreground border border-border",
                    message.role === 'system' ? 'w-full text-center bg-transparent border-none shadow-none' : '',
                    message.status === 'pending' || message.status === 'failed' ? 'opacity-70' : ''
                  )}
                >
                    <p className="whitespace-pre-wrap">{message.content}</p>
                </div>
                {message.role === "user" && (
                  <div className="flex flex-col items-center gap-1">
                    <Avatar>
                      <AvatarFallback className="bg-secondary text-secondary-foreground">
                        <User />
                      </AvatarFallback>
                    </Avatar>
                    {message.status === 'pending' && (
                       <Tooltip>
                        <TooltipTrigger><Clock className="h-4 w-4 text-muted-foreground" /></TooltipTrigger>
                        <TooltipContent><p>{dict.chat.status.pending}</p></TooltipContent>
                      </Tooltip>
                    )}
                    {message.status === 'failed' && (
                       <Tooltip>
                        <TooltipTrigger asChild>
                           <Button variant="ghost" size="icon" className="h-6 w-6" onClick={() => handleRetryMessage(message)}>
                             <RefreshCw className="h-4 w-4 text-destructive" />
                           </Button>
                        </TooltipTrigger>
                        <TooltipContent><p>{dict.chat.status.failed}</p></TooltipContent>
                      </Tooltip>
                    )}
                  </div>
                )}
              </motion.div>
            ))}
          </AnimatePresence>
          </TooltipProvider>
          {isLoading && isOnline && (
            <div className="flex items-start gap-4 justify-start">
               <Avatar className="border-2 border-primary/50 shadow-md shadow-primary/20">
                <AvatarFallback className="bg-transparent text-primary"><HerLogo className="h-6 w-6" /></AvatarFallback>
              </Avatar>
              <div className="flex items-center space-x-2 rounded-xl bg-card px-4 py-3 text-sm shadow-md border border-border">
                <Loader2 className="h-5 w-5 animate-spin text-muted-foreground" />
                <span className="text-muted-foreground">{dict.chat.thinking}</span>
              </div>
            </div>
          )}
          <div ref={messagesEndRef} />
        </div>
      </ScrollArea>

      <div className="border-t border-primary/20 bg-card/80 p-4">
         {shouldShowSummaryButton && (
            <motion.div
                initial={{ opacity: 0, y: 10 }}
                animate={{ opacity: 1, y: 0 }}
                className="mb-4"
            >
                <Button onClick={handleGenerateSummary} className="w-full" variant="outline" disabled={!isOnline || isSummarizing}>
                    {isSummarizing ? (
                        <Loader2 className="mr-2 h-4 w-4 animate-spin" />
                    ) : (
                        <BookCheck className="mr-2 h-4 w-4" />
                    )}
                    {isSummarizing 
                        ? dict.summary.manualGenerate.inProgress 
                        : (isLimitReached ? dict.summary.manualGenerate.buttonLimit : dict.summary.manualGenerate.buttonDefault)
                    }
                </Button>
            </motion.div>
        )}
        {shouldShowLimitNotice && isOnline && !isLimitReached && (
            <Alert variant="default" className="mb-4">
                <AlertTriangle className="h-4 w-4" />
                <AlertTitle>{dict.chat.limitWarningTitle}</AlertTitle>
                <AlertDescription>
                    {`${dict.chat.limitWarningDesc} ${messagesLeft}.`}
                </AlertDescription>
            </Alert>
        )}
        {!isOnline && (
             <div className="flex-1 flex items-center justify-center text-sm text-muted-foreground bg-muted p-2 rounded-md mb-4">
                <WifiOff className="h-4 w-4 mr-2" />
                {dict.chat.offlinePlaceholder}
             </div>
          )}
        <form onSubmit={handleSubmit} className="flex items-center gap-2">
          <Input
            value={input}
            onChange={(e) => setInput(e.target.value)}
            placeholder={getPlaceholderText()}
            className="flex-1"
            disabled={isChatDisabled}
            autoComplete="off"
          />

          {isMicAvailable && (
            <Button type="button" size="icon" variant={isListening ? "destructive" : "outline"} onClick={toggleListening} disabled={isChatDisabled}>
                {isListening ? (
                    <div className="relative flex items-center justify-center">
                        <Mic className="h-5 w-5" />
                        <span className="absolute h-2 w-2 bg-white rounded-full animate-ping"></span>
                    </div>
                ) : <Mic className="h-5 w-5" />}
              <span className="sr-only">{isListening ? "Stop listening" : "Start listening"}</span>
            </Button>
          )}

          <Button type="submit" size="icon" disabled={isChatDisabled || !input.trim() || isListening}>
            {isLoading && isOnline ? <Loader2 className="h-5 w-5 animate-spin" /> : <Send className="h-5 w-5" />}
            <span className="sr-only">{dict.chat.sendButton}</span>
          </Button>
        </form>
      </div>
    </div>
  );
}

// nuxt-app/pages/chat.vue
<template>
  <div class="flex flex-col h-full bg-background/80 backdrop-blur-sm rounded-lg border border-primary/20 shadow-lg shadow-primary/10">
    <ScrollArea class="flex-1 p-4">
      <div class="space-y-6">
        <TooltipProvider>
          <!-- Messages will be rendered here -->
          <div v-for="message in messages" :key="message.id" :class="cn('flex items-start gap-4', message.role === 'user' ? 'justify-end' : 'justify-start')">
            <template v-if="message.role === 'assistant'">
              <Avatar class="border-2 border-primary/50 shadow-md shadow-primary/20">
                <AvatarFallback class="bg-transparent text-primary">
                  <!-- <HerLogo class="h-6 w-6" /> -->
                </AvatarFallback>
              </Avatar>
            </template>
            <div :class="cn('max-w-md rounded-xl px-4 py-3 text-sm shadow-md', message.role === 'user' ? 'bg-primary text-primary-foreground shadow-primary/30' : 'bg-card text-card-foreground border border-border', message.role === 'system' ? 'w-full text-center bg-transparent border-none shadow-none' : '', message.status === 'pending' || message.status === 'failed' ? 'opacity-70' : '')">
              <p class="whitespace-pre-wrap">{{ message.content }}</p>
            </div>
            <template v-if="message.role === 'user'">
              <div class="flex flex-col items-center gap-1">
                <Avatar>
                  <AvatarFallback class="bg-secondary text-secondary-foreground">
                    <User class="h-5 w-5" />
                  </AvatarFallback>
                </Avatar>
                <Tooltip v-if="message.status === 'pending'">
                  <TooltipTrigger><Clock class="h-4 w-4 text-muted-foreground" /></TooltipTrigger>
                  <TooltipContent><p>Pending</p></TooltipContent>
                </Tooltip>
                <Tooltip v-if="message.status === 'failed'">
                  <TooltipTrigger as-child>
                    <Button variant="ghost" size="icon" class="h-6 w-6">
                      <RefreshCw class="h-4 w-4 text-destructive" />
                    </Button>
                  </TooltipTrigger>
                  <TooltipContent><p>Failed to send</p></TooltipContent>
                </Tooltip>
              </div>
            </template>
          </div>
          <!-- Loading indicator -->
          <div v-if="isLoading" class="flex items-start gap-4 justify-start">
            <Avatar class="border-2 border-primary/50 shadow-md shadow-primary/20">
              <AvatarFallback class="bg-transparent text-primary">
                <!-- <HerLogo class="h-6 w-6" /> -->
              </AvatarFallback>
            </Avatar>
            <div class="flex items-center space-x-2 rounded-xl bg-card px-4 py-3 text-sm shadow-md border border-border">
              <Loader2 class="h-5 w-5 animate-spin text-muted-foreground" />
              <span class="text-muted-foreground">Thinking...</span>
            </div>
          </div>
        </TooltipProvider>
      </div>
    </ScrollArea>

    <div class="border-t border-primary/20 bg-card/80 p-4">
      <!-- Summary button -->
      <div v-if="shouldShowSummaryButton" class="mb-4">
        <Button class="w-full" variant="outline" :disabled="!isOnline || isSummarizing">
          <Loader2 v-if="isSummarizing" class="mr-2 h-4 w-4 animate-spin" />
          <BookCheck v-else class="mr-2 h-4 w-4" />
          <span>Generate Summary</span>
        </Button>
      </div>
      <!-- Limit warning -->
      <Alert v-if="shouldShowLimitNotice" variant="default" class="mb-4">
        <AlertTriangle class="h-4 w-4" />
        <AlertTitle>Message limit warning</AlertTitle>
        <AlertDescription>
          You are approaching your daily message limit.
        </AlertDescription>
      </Alert>
      <!-- Offline notice -->
      <div v-if="!isOnline" class="flex-1 flex items-center justify-center text-sm text-muted-foreground bg-muted p-2 rounded-md mb-4">
        <WifiOff class="h-4 w-4 mr-2" />
        You are offline. Messages will be sent when you reconnect.
      </div>
      <form @submit.prevent="handleSubmit" class="flex items-center gap-2">
        <Input
          v-model="input"
          placeholder="Type your message..."
          class="flex-1"
          autocomplete="off"
        />
        <Button type="button" size="icon" variant="outline">
          <Mic class="h-5 w-5" />
          <span class="sr-only">Start listening</span>
        </Button>
        <Button type="submit" size="icon">
          <Send class="h-5 w-5" />
          <span class="sr-only">Send</span>
        </Button>
      </form>
    </div>
  </div>
</template>

<script setup lang="ts">
import { ref, computed, onMounted, nextTick, watch } from 'vue'
import { useAppStore, type Message } from '~/stores/app'
import { storeToRefs } from 'pinia'
import { cn } from '@/lib/utils'
import { useOnline } from '@vueuse/core'

// Import lucide-vue-next icons
import { User, Clock, RefreshCw, Loader2, BookCheck, AlertTriangle, WifiOff, Mic, Send } from 'lucide-vue-next'

// Import shadcn-vue components
import { Button } from '@/components/ui/button'
import { Input } from '@/components/ui/input'
import { ScrollArea } from '@/components/ui/scroll-area'
import { Avatar, AvatarFallback } from '@/components/ui/avatar'
import { Alert, AlertDescription, AlertTitle } from '@/components/ui/alert'
import { Tooltip, TooltipContent, TooltipProvider, TooltipTrigger } from '@/components/ui/tooltip'

// Mock AI flow
const generateConversationalResponse = async (options: any) => {
  console.log("Generating AI response with options:", options);
  return new Promise(resolve => {
    setTimeout(() => {
      resolve({ response: "This is a mock response from the oracle." });
    }, 1500);
  });
};


const appStore = useAppStore()
const { messages, userFacts, userName, userGender, oraclePersonality, language } = storeToRefs(appStore)
const { addMessage, updateMessageStatus, getConversationHistory, getTodaysUserMessageCount, getDatesNeedingSummary, hasDoneTarotReadingToday, setLastTarotReadingDate } = appStore

const input = ref('')
const isLoading = ref(false)
const isSummarizing = ref(false)
const isListening = ref(false) // Placeholder for speech recognition
const messagesEndRef = ref<HTMLDivElement | null>(null)

const isOnline = useOnline()

const MESSAGE_LIMIT = 20;
const WARNING_THRESHOLD = 5;

const userMessageCount = computed(() => getTodaysUserMessageCount())
const messagesLeft = computed(() => MESSAGE_LIMIT - userMessageCount.value)
const isLimitReached = computed(() => messagesLeft.value <= 0)
const shouldShowLimitNotice = computed(() => messagesLeft.value <= WARNING_THRESHOLD && !isLimitReached.value)
const datesToSummarize = computed(() => getDatesNeedingSummary())
const shouldShowSummaryButton = computed(() => datesToSummarize.value.length > 0 || isLimitReached.value)

const getPlaceholderText = computed(() => {
  if (isListening.value) return "Listening...";
  if (isLimitReached.value) return "You have reached your daily message limit.";
  if (datesToSummarize.value.length > 0) return "Please generate a summary before continuing.";
  return "Type your message...";
});

const isChatDisabled = computed(() => isLoading.value || isSummarizing.value || (isOnline.value && datesToSummarize.value.length > 0) || isLimitReached.value)

const handleSendMessage = async (messageContent: string, messageId: string) => {
  updateMessageStatus(messageId, 'pending');
  isLoading.value = true;

  try {
    const result = await generateConversationalResponse({
      message: messageContent,
      conversationHistory: getConversationHistory(),
      userFacts: userFacts.value.map(f => f.fact),
      language: language.value,
      tarotReadingDone: hasDoneTarotReadingToday(),
      userName: userName.value,
      userGender: userGender.value,
      personality: oraclePersonality.value,
    });

    const aiMessage: Omit<Message, 'id' | 'timestamp'> = { role: "assistant", content: result.response, status: 'sent' };
    addMessage(aiMessage);
    updateMessageStatus(messageId, 'sent');

    const readingKeywords = ['past:', 'presente:', 'futuro:'];
    const lowerCaseResponse = result.response.toLowerCase();

    if (!hasDoneTarotReadingToday() && readingKeywords.some(kw => lowerCaseResponse.includes(kw))) {
      setLastTarotReadingDate(new Date().toISOString());
    }

  } catch (error) {
    console.error("Error generating response:", error);
    updateMessageStatus(messageId, 'failed');
    // You might want to use a toast notification here
  } finally {
    isLoading.value = false;
  }
}

const handleSubmit = async () => {
  if (!input.value.trim() || isChatDisabled.value) return;

  const messageContent = input.value;
  input.value = "";

  const userMessage: Omit<Message, 'id' | 'timestamp'> = {
      role: "user",
      content: messageContent,
      status: isOnline.value ? 'pending' : 'pending' // Always pending at first
  };
  const messageId = addMessage(userMessage);

  if (isOnline.value) {
    await handleSendMessage(messageContent, messageId);
  } else {
    // Logic for offline queue will be handled by the store's processOfflineQueue method
    // which can be triggered when isOnline becomes true.
    console.log("Message queued for sending when online.");
  }
};

const handleRetryMessage = (message: Message) => {
    if(isOnline.value) {
      handleSendMessage(message.content, message.id);
    } else {
      console.log("Cannot retry message. Still offline.");
    }
}

const scrollToBottom = () => {
  nextTick(() => {
    messagesEndRef.value?.scrollIntoView({ behavior: "smooth" });
  });
};

onMounted(() => {
  appStore.initializeMessages("Welcome! How can I help you today?");
  scrollToBottom();
});

watch(messages, () => {
  scrollToBottom();
}, { deep: true });

// Watch for coming back online to process queue
watch(isOnline, (online) => {
  if (online) {
    console.log("Back online, processing queue...");
    // appStore.processOfflineQueue(); // TODO: Implement this in the store
  }
});

</script>
